version: "3"

services: 
  db: 
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=nodeauth
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  app:
    build: .
    command: npm start
    depends_on: 
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
